_wandb:
    value:
        cli_version: 0.21.0
        e:
            v3bv3lj09a6z47f85a36r2svzxg6fpj3:
                args:
                    - --train-cnn
                codePath: .charles/spectrogram.py
                codePathLocal: spectrogram.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "450971566080"
                        used: "278386671616"
                email: charles.cai@socialogix.net
                executable: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles/.venv/bin/python3
                git:
                    commit: 3f7da43794d17378dd7de7fe3b7ff9279f6479fe
                    remote: https://github.com/AdamBeedell/MLX8-WS-Audio-Transformer.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-b989f6ba-23c4-1b2f-58ec-ba90b216e722
                host: bbe0d4c6f2be
                memory:
                    total: "67250049024"
                os: Linux-6.6.78-Unraid-x86_64-with-glibc2.35
                program: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles/spectrogram.py
                python: CPython 3.10.0
                root: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles
                startedAt: "2025-07-08T11:40:06.537388Z"
                writerId: v3bv3lj09a6z47f85a36r2svzxg6fpj3
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
batch_size:
    value: 16
dropout:
    value: 0.3
epochs:
    value: 20
lr:
    value: 0.0003
n_classes:
    value: 10
n_mels:
    value: 128
weight_decay:
    value: 0.0001
