_wandb:
    value:
        cli_version: 0.21.0
        e:
            139b3n6gntysekrhk04egyb900w7jcr4:
                args:
                    - --test
                codePath: .charles/spectrogram.py
                codePathLocal: spectrogram.py
                email: charles.cai@socialogix.net
                executable: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles/.venv/bin/python3
                git:
                    commit: f2b49294dc1d99894e325eda4e0d44c600cc1de8
                    remote: https://github.com/AdamBeedell/MLX8-WS-Audio-Transformer.git
                host: bbe0d4c6f2be
                os: Linux-6.6.78-Unraid-x86_64-with-glibc2.35
                program: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles/spectrogram.py
                python: CPython 3.10.0
                root: /workspace/_github/AdamBeede/MLX8-WS-Audio-Transformer/.charles
                startedAt: "2025-07-07T18:15:31.388579Z"
                writerId: 139b3n6gntysekrhk04egyb900w7jcr4
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.0
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
dropout:
    value: 0.3
n_classes:
    value: 10
n_mels:
    value: 64
test_checkpoint:
    value: 10_urbansound8k_cnn.pt
